title: Michał Jeznach
description: Data Analyst
site_title: 'Michał Jeznach - Get to know me!'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Yeznach
blog_url: 
email: jeznachmichal1@gmail.com
keybase_username: yeznach
twitter_username: _
reddit_username: yeznach

# absolute or relative
profile_picture: assets/images/profile_pic.JPG

# Google Analytics ID
google_analytics: 
