title: Michał Jeznach
description: Data Analyst
site_title: '@abhn - Abhishek Nagekar'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: abhn
blog_url: https://www.nagekar.com
email: jeznachmichal1@gmail.com
keybase_username: yeznach
twitter_username: _
reddit_username: yeznach

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
